### PR TITLE
'Request edit' button

### LINKED ISSUE #1027: "request edit rights" button shown when edit rights were already given
### Contribution guidelines

- [X] I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I've read the [Common issues documentation section](https://docs.cryptpad.org/en/FAQ.html#common-issues) and I also checked [previous issues](https://github.com/xwiki-labs/cryptpad/issues).

### Description

In a pad stored in my drive with edit rights but owned by another user, the access modal shows the "request edit rights" button even though I already have edit rights. Thanks to @ansuz for reporting this. 

### Steps to reproduce

1. User Billy creates a document (Code)
2. Shares an edit link with Alice
3. Alice opens document (stores in Drive or not)
4. Alice opens Access modal
5. Alice sees "Request Edit Rights" button

### Expected behavior

"Request edit rights" should not be shown if you already have edit rights

### System information

| Question | Answer |
| --- | --- |
| Operating system and version | Pop_OS! 22.04 |
| Web browser and version| Billy Firefox 112.0.1, Alice Chromium 109.0.5414.119 |
| Extensions installed | NA |
| Browser tweaks | NA |
| CryptPad version | reproduced in 5.3.0 and 5.2.1 |

### PR DESCRIPTION
**Pull request by zuzanna-maria**
* 'Request edit' button in Access modal no longer displayed if user already has edit access (fixes #1027)

### CODE REVIEW

**Review by yflory — APPROVED** [review]

File: www/common/inner/common-modal.js [hunk 1]
```diff
@@ -49,7 +49,13 @@ define([
                         // Access modal and the pad is not stored: get the hashes from outer
                         var hashes = priv.hashes || {};
                         // For calendars, individual href is passed via opts
-                        data.href = ((priv.app === 'calendar') && opts.href) || Hash.hashToHref(hashes.editHash || hashes.fileHash, priv.app);
+                        if (priv.app === 'calendar') {
+                            data.href = (priv.app === 'calendar') && opts.href;
```
Comment (yflory) [inline www/common/inner/common-modal.js:53]: Here you don't need to check if the app is `calendar` in the assignment since it's already checked in the parent `if`. `data.href = opts.href;` is enough

File: www/common/inner/common-modal.js [hunk 2]
```diff
@@ -49,7 +49,13 @@ define([
...
+                        } else if (hashes.editHash || hashes.fileHash) {
+                            data.href = Hash.hashToHref(hashes.editHash || hashes.fileHash);
```
Comment (yflory) [inline www/common/inner/common-modal.js:55]: You forgot `priv.app` as the second argument so we end up with the "undefined" app:
`http://localhost:3000/undefined/#/2/code/edit/DRlul1bzt7FpOdlzik8ZLA2F/`

**Review by yflory — CHANGES_REQUESTED** [review]

**Review by yflory — APPROVED** [review]
