### PR TITLE
Prevent saving file to Drive multiple times

### LINKED ISSUE #1745: Files can be stored in CryptDrive multiple times
### Description

The 'Store in CryptDrive' function creates multiple Drive shortcuts for the same file

### Steps to reproduce

1. Go to e.g. [cryptpad.fr/pad](http://cryptpad.fr/pad) and create a new Pad document
2. Click 'Store' on the popup that asks if file should be saved -- file appears in Drive
3. File menu > 'Store in CryptDrive' -- every time 'Store in CryptDrive' is clicked creates a new shortcut

### Relevant logs

_No response_

### Expected behavior

Only one shortcut per file should be created in the Drive -- clicking 'Store in CryptDrive' multiple times should produce an alert that file is already stored

### Which operating system are you using?

_No response_

### What browsers are you seeing the problem on?

_No response_

### Extensions

n/a

### Version

2024.12.0

### PR DESCRIPTION
**Pull request by zuzanna-maria**
- Fixes #1745 (can no longer save file to drive if already saved)

### CODE REVIEW

File: www/common/common-ui-elements.js [hunk 1]
```diff
@@ -594,16 +594,19 @@ define([
...
+        let btnVisibility = $button.attr('style');
         if (btnClass) { attributes['class'] = btnClass; }
         if (btnId) { attributes['id'] = btnId; }
         if (btnTitle && !attributes.title) { attributes['title'] = btnTitle; }
-
+        if (btnVisibility) { attributes['style'] = btnVisibility; }
         return UIElements.createDropdownEntry({
             tag: 'a',
             attributes: attributes,
+            style: style,
```
Comment (yflory) [inline www/common/common-ui-elements.js:609]: I'm not sure I understand why we have a "style" element here if we already have `attributes['style']` above. It seems like one will override the other.

File: www/common/common-ui-elements.js [hunk 2]
```diff
@@ -3349,7 +3352,7 @@ define([
         if (data && data.stored) {
             if (!data.inMyDrive) {
                 $('.cp-toolbar-storeindrive').show();
-            }
+            }
```
Comment (yflory) [inline www/common/common-ui-elements.js:3355]: "Space" character to remove

File: www/common/drive-ui.js [hunk 3]
```diff
@@ -5094,9 +5094,9 @@ define([
                 sframeChan.query('Q_STORE_IN_TEAM', {
                     href: data.href || data.rohref,
                     password: data.password,
-                    path: paths[0].path[0] === 'template' ? ['template'] : undefined,
                     title: data.title || '',
-                    teamId: -1
+                    teamId: -1,
+                    path: paths[0].path[0] === 'template' ? ['template'] : undefined
```
Comment (yflory) [inline www/common/drive-ui.js:5099]: Try to keep the original order to avoid unnecessary diff :)

File: www/common/outer/async-store.js [hunk 4]
```diff
@@ -1220,7 +1221,20 @@ define([
                 if (!s.id) { inMyDrive = res.length; }
 
                 Array.prototype.push.apply(allData, res);
+
+                if (res && res[0]) {
+                    var elementPath = store.manager.user.userObject.findFile(res[0].id)[0];
```
Comment (yflory) [inline www/common/outer/async-store.js:1226]: Multiple issues here:
1. "res" may reference data from a team drive but you're trying to search the path from your own drive
2. "res" is an array because the pad may be stored in your drive multiple times. You're pushing to the array only the path of the first occurence found

File: www/common/outer/async-store.js [hunk 5]
```diff
@@ -1220,7 +1221,20 @@ define([
...
+                    if (elementPath) {
+                        path.push(elementPath);
+                    }
+                }    
+
             });
+
+            if (path[0]) {
```
Comment (yflory) [inline www/common/outer/async-store.js:1234]: I don't really understand why `path` should be an array in you only use the first entry

File: www/common/outer/async-store.js [hunk 6]
```diff
@@ -1287,6 +1300,8 @@ define([
                     });
                     return;
                 }
+            } else if (inTrash) {
+                store.manager.user.userObject.restore(path[0]);
```
Comment (yflory) [inline www/common/outer/async-store.js:1304]: If I understand correctly (I didn't test), it seems this is going to restore any pads from your drive that you open. This function is called everytime someone opens a document, updates its title or tries to store it. This isn't something we really want (trashed document should stay there unless there is an explicit action to restore them).

**Review by yflory — CHANGES_REQUESTED** [review]
The latest changes seem a bit out of scope for this PR. They aren't about preventing multiple save anymore but about restoring documents from the trash.
The initial goal of the PR was to fix a clear issue, but the part about the trash may change the user experience and probably requires further discussions about how to handle this issue.

File: www/common/outer/async-store.js [hunk 7]
```diff
@@ -1253,7 +1253,7 @@ define([
                 }
                 obj.userObject.setHref(channel, null, href);
             });
-
+
```
Comment (Chouhartem) [inline www/common/outer/async-store.js:1256]: trailing spaces to remove

**Review by yflory — APPROVED** [review]
